# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170905_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='purchase_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='doi',
            field=models.CharField(blank=True, help_text='10.xxx/1234', max_length=200, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_loc',
            field=models.CharField(max_length=100, verbose_name='Publisher location'),
        ),
    ]
