# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 11:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import plugins.books.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170905_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_open_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/vol/janeway/src/media'), upload_to=plugins.books.models.cover_images_upload_path),
        ),
    ]
