# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 15:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plugins.books.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20190405_1549'),
        ('books', '0005_auto_20190624_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('download', 'Download'), ('view', 'View')], max_length=20)),
                ('accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ajrbyers/janeway/src/media'), upload_to=plugins.books.models.cover_images_upload_path),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Format'),
        ),
    ]
