# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
