# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_chapter_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sequence', 'number')},
        ),
        migrations.AddField(
            model_name='contributor',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='contributors',
            field=models.ManyToManyField(null=True, related_name='chapter_contributors', to='books.Contributor'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='The chapter number eg. 1', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sequence',
            field=models.PositiveIntegerField(help_text='The order in which the chapters should appear.'),
        ),
    ]
