# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190731_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='chapter',
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.AlterField(
            model_name='bookaccess',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Format'),
        ),
    ]
