# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200728_1441'),
        ('books', '0012_auto_20200909_1547'),
    ]

    operations = [
    ]
