# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_merge_20200929_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_title',
            field=models.BooleanField(default=True, help_text='Mark as false if you want to hide the category title.'),
        ),
    ]
