# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210511_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='buy_button_text',
            field=models.CharField(default='Buy this Book', max_length=100),
        ),
    ]
