# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_category_buy_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='license_information',
            field=models.TextField(blank=True, help_text='Add copyright and/or license information here.', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='license_information',
            field=models.TextField(blank=True, help_text='Add copyright and/or license information here. If left blank will display book version of this field.', null=True),
        ),
    ]
