# Generated by Django 4.2.15 on 2024-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_bookaccess_chapter_alter_bookaccess_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='peer_reviewed',
            field=models.BooleanField(default=False, help_text='Mark if this book has been peer reviewed.'),
        ),
        migrations.AddField(
            model_name='booksetting',
            name='display_review_status',
            field=models.BooleanField(default=False, help_text="Mark this to display a book's review status."),
        ),
    ]
