# Generated by Django 4.2.20 on 2025-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_book_peer_reviewed_booksetting_display_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, null=True),
        ),
    ]
