# Generated by Django 4.2.20 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='display_read_link',
            field=models.BooleanField(default=True, help_text='For EPUB only, check if you want a Read this Book link'),
        ),
    ]
