# Generated by Django 4.2.20 on 2026-03-13 16:52

import core.file_system
from django.db import migrations, models
import plugins.books.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_book_language_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='headshot',
            field=models.FileField(blank=True, null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=plugins.books.models.headshot_upload_path),
        ),
    ]
