# Generated by Django 4.2.20 on 2026-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_contributor_bio_and_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='corporate_name',
            field=models.CharField(blank=True, help_text='Full name of the organisation (used when Is Corporate is checked).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='Check if this contributor is a corporate/organisational author.'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
