# Generated by Django 4.2.20 on 2026-03-13 20:43

from django.db import migrations, models


def migrate_category_to_categories(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.filter(category__isnull=False):
        book.categories.add(book.category)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_contributor_corporate_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.category'),
        ),
        migrations.RunPython(
            migrate_category_to_categories,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
